# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Package app with pyinstaller
      run: |
        python -c "with open('termtyper.py', 'w') as f: f.write('from termtyper import main\nmain()\n')"
        pyinstaller -F termtyper.py -i pic.ico
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: termtyper-windows
        path: ./dist/termtyper.exe

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Package app with pyinstaller
      run: |
        python -c "with open('termtyper.py', 'w') as f: f.write('from termtyper import main\nmain()\n')"
        pyinstaller -F termtyper.py -i pic.ico
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: termtyper-linux
        path: ./dist/termtyper

  macOS-build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Package app with pyinstaller
      run: |
        python -c "with open('termtyper.py', 'w') as f: f.write('from termtyper import main\nmain()\n')"
        pyinstaller -F termtyper.py -i pic.ico
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: termtyper-macos
        path: ./dist/termtyper
